#!/bin/bash
make clean && make
./gol $1 inputs/$2.pbm outputs/$2_par_$1.pbm
./../orig_hw5/gol $1 inputs/$2.pbm ../orig_hw5/outputs/$2_seq_$1.pbm
diff outputs/$2_par_$1.pbm ../orig_hw5/outputs/$2_seq_$1.pbm
